### ISSUE TITLE
serial port not showing up

### ISSUE THREAD

**Issue by FirewallDaProtogen** [provrb/obdium#19]
i have an elm327 usb adapter and it shows up in dmesg, and i have added my user to the dialout group, but it doesnt show up in the software when i press refresh

**Comment by jaschum** [comment]
I am also facing this issue. The dropdown for COM port selection only shows "demo mode" while the device manager lists three available com ports (one being an ELM based OBD2 adapter):

<img width="822" height="156" alt="Image" src="https://github.com/user-attachments/assets/0aa694b0-d88f-43a9-bd48-4900535e6472" />

<img width="610" height="230" alt="Image" src="https://github.com/user-attachments/assets/8025ee70-eacc-4304-b1cf-5f1e0ca7ca72" />

I did use the refresh button on top of the dropdown but that does not change anything.

I am using Windows 11 on an ARM64 architecture, so OBDium is running in emulation mode. Not sure if that might cause it for me as I succesfully used other x64 OBD software with the same adapter on the same PC.

Does the vehicle manufacturer and physical connection state matter for the COM port list display?

**Comment by rabarar** [comment]
I am using this on a Mac OSX Tahoe 26.4.1 - also not seeing the serial port even though it's there `/dev/tty.usb...`

**Comment by provrb** [comment]
😭😭 okay. Can you try pulling from the `tauri-v2-migration` branch or downloading the code in the `v1.5.0-unstable` release published earlier today to see if the issue persists there? These ship with a potential fix to this issue.

**Comment by rabarar** [comment]
pulled and built the branch - i see the serial port on my MacBook pro `/dev/tty.usbserial-10` but when i run the app, i see no port listed. I do not have the OBD2 plugged into the car, but that shouldn’t matter to show the port, correct?

also, your build fails unless you generate an app icon for the app `cargo tauri icon obdium.png`  where you create a square-dimensioned png file to use as the app icon

**Comment by aatanvardoo** [comment]
> pulled and built the branch - i see the serial port on my MacBook pro `/dev/tty.usbserial-10` but when i run the app, i see no port listed. I do not have the OBD2 plugged into the car, but that shouldn’t matter to show the port, correct?
> 
> also, your build fails unless you generate an app icon for the app `cargo tauri icon obdium.png`  where you create a square-dimensioned png file to use as the app icon
> […](#)

Windows user here. 
Doesn't matter if plugged into car or not. 
check if Your elm327 adapter runs at default 38400 as Obdium pings com port at this fixed baud rate. 
There is elmconfig tool available(for windows) to verify/change baud rate

**Comment by provrb** [comment]
> check if Your elm327 adapter runs at default 38400 as Obdium pings com port at this fixed baud rate.

should be fixed and adjusted in #33 and pushed to main. completely forgot it did this; I haven't worked on that part of the project in a minute. should be more reliable now. please let me know if this persists for real this time.

**Comment by MstrGecko** [comment]
I'm still experiencing this issue.  I can't get this to work on either Windows11 or Arch Linux(my primary: Plasma, Wayland) yet. my adapter is a VeePeak OBDCheck BLE +. being a BLE, i have to assign it's serial port manually, but even then, Obdium appears to not see the comport where i bound it(i'm having to use rfcomm, so it's naturally at /dev/rfcomm0), or any of the symlinks.  on Linux, i'm using a git pull that up to date as of today, 13 Jul 2026. but on Windows i'm using the 1.5.1 release exe. If you can repair the functionality so that it will detect a serial port ANYWHERE, i just need to know where to symlink it to.  Adapter is known good because Dr. Prius can access it and read battery module voltages.

**Comment by provrb** [comment]
I've only ever tested this with a cheap ELM327 USB adapter, so I'm not sure how reliable the app would be with other devices, though theoretically I don't think it should matter. If possible, can you try and run OBDium in a terminal using `cargo tauri dev`, scanning for serial ports using the refresh button, and then posting the command-line output. It should contain something like `"- response: `{}` for port: {}"` or `"Ports: {:?}"` (you can see the implementation for getting all open serial ports [here](https://github.com/provrb/obdium/blob/9dc97f36567cdbc3abb4e331882121d071976550/backend/src/obd.rs#L271)). This will display all serial port responses to the `ATI` ELM command as well as the name of the port. It is possible that your adapter is not responding to this command, thus being filtered out. But once we see the output, we can proceed further. Sorry for the inconvenience.

**Comment by infiniteoil** [comment]
Hey all, I've been trying to troubleshoot this for a while but with no success sadly. Here's my summary of problems that I've encountered with hopefully all the necessary information to help for a fix :)

**Environment and gear used**

Linux Mint, built from main @ commit 9dc97f3
Adapter: Veepeak OBDCheck BLE+ — paired as BLE-only (GATT services only, no SPP UUID in bluetoothctl info), despite being marketed as BLE+Classic
Using [ble-serial](https://github.com/Jakeler/ble-serial) to bridge the BLE GATT UART service to a virtual pty at /tmp/ttyBLE, since rfcomm (Classic Bluetooth) doesn't apply to this device

**Symptom**

OBD::connect() consistently fails at the ATE0 step of init() with Error::InitFailed ("failed to initialize obd with ecu"), even though:

The adapter itself responds correctly to manual testing (minicom, and raw echo > /tmp/ttyBLE writes all get clean ATE0\rOK\r\r> replies)
ATZ (the first init command) always succeeds
ATSP0 (sent later in connect(), after init()) always succeeds

**Diagnostics performed**

Confirmed via serialport::available_ports() that port enumeration doesn't detect /dev/rfcomm* or the ble-serial virtual pty at all (separate issue, worked around locally by manually scanning for these paths in get_open_serial_ports())
Ran ble-serial -v alongside OBDium to capture raw BLE traffic during a real connect attempt. The wire trace shows ATZ succeeding, then jumps straight to a later command — ATE0, ATL0, ATH1 never appear on the wire at all during a real connect() call
Added debug prints directly to send_command() — confirmed write_all() for ATE0's bytes ([65, 84, 69, 48, 13]) returns Ok, with no error, yet those bytes never arrive at ble-serial's pty reader
Ruled out stream.clear(serialport::ClearBuffer::All) (called before every write in send_command) as the cause — disabling it made no difference
Ruled out simple BLE latency/timing — added explicit delays after ATZ and between init commands, no change

**Current working theory**

Something causes bytes written via write_all() to be silently lost between OBDium and the pty specifically for BLE-bridged virtual serial devices — write returns success at the OS level but the data never reaches the reader on the other end. Suspect two file handles/connections may briefly coexist on the same port (though the frontend's get-serial-ports scan appears to only fire once on load, several seconds before connect() runs, so this isn't confirmed). A real USB/rfcomm serial device would normally reject a second concurrent open() outright, which may be why this doesn't surface on non-BLE hardware.

**Not yet resolved** :(  happy to keep providing diagnostics/logs if useful, I also have raw byte-level traces available.

Would love to see this project take off reliably, let me know if there's anything else I can do to help.
